name: CI/CD

on:
  push:
    branches: [main]
    tags: ["v[0-9]*.[0-9]*.[0-9]*"]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository.
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up pnpm (using a fixed version).
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
          run_install: false

      # 3. Set up Node.js (using the latest LTS version) and enable pnpm caching.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: pnpm

      # 4. Install project dependencies.
      - name: Install
        run: pnpm install --frozen-lockfile

      # 5. Lint the code.
      - name: Lint
        run: pnpm lint

      # 6. Check code formatting.
      - name: Format
        run: pnpm format

      # 7. Build the project.
      - name: Build
        run: pnpm build

      # 8. Run tests.
      - name: Test
        run: pnpm test

      # 9. Configure npm auth and publish the package if a tag is pushed.
      - name: Publish Package
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          pnpm publish --no-git-checks
